# Generated by Django 5.2 on 2025-04-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_acessorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessorio',
            name='nome',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='acessorio',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
