# Generated by Django 5.2 on 2025-04-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cor_alter_acessorio_descricao_alter_acessorio_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('categoria', models.CharField(blank=True, max_length=80)),
            ],
        ),
    ]
